//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.04 at 08:02:56 PM GST 
//


package com.daimler.adx.integration.paragon.invoiceimport.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.daimler.adx.integration.paragon.invoiceimport.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.daimler.adx.integration.paragon.invoiceimport.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MTIF63INVOICEREQ }
     * 
     */
    public MTIF63INVOICEREQ createMTIF63INVOICEREQ() {
        return new MTIF63INVOICEREQ();
    }

    /**
     * Create an instance of {@link MTIF63INVOICEREQ.Request }
     * 
     */
    public MTIF63INVOICEREQ.Request createMTIF63INVOICEREQRequest() {
        return new MTIF63INVOICEREQ.Request();
    }

    /**
     * Create an instance of {@link MTIF63INVOICEREQ.Request.Login }
     * 
     */
    public MTIF63INVOICEREQ.Request.Login createMTIF63INVOICEREQRequestLogin() {
        return new MTIF63INVOICEREQ.Request.Login();
    }

    /**
     * Create an instance of {@link MTIF63INVOICEREQ.Request.Invoices }
     * 
     */
    public MTIF63INVOICEREQ.Request.Invoices createMTIF63INVOICEREQRequestInvoices() {
        return new MTIF63INVOICEREQ.Request.Invoices();
    }

}
