//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.04 at 08:02:56 PM GST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dcx.com.xi/paragon/services/IF63/InvoicePDF")
package com.daimler.adx.integration.paragon.invoiceimport.request;
